#!/bin/bash
# Script pour corriger les permissions MySQL et appliquer les optimisations
# À exécuter sur le serveur avec les droits ROOT

echo "🔧 Correction des permissions MySQL"
echo "=================================="

# Option 1 : Se connecter en root MySQL et appliquer
echo "Exécutez ces commandes MANUELLEMENT :"
echo ""
echo "1️⃣ Se connecter à MySQL en root :"
echo "   mysql -u root -p"
echo ""
echo "2️⃣ Copier-coller ces commandes dans MySQL :"
echo ""
echo "SET GLOBAL max_connections = 300;"
echo "SET GLOBAL innodb_buffer_pool_size = 17179869184;"
echo "SET GLOBAL query_cache_type = 1;"
echo "SET GLOBAL query_cache_size = 268435456;"
echo "SET GLOBAL query_cache_limit = 2097152;"
echo "SET GLOBAL thread_cache_size = 16;"
echo "SET GLOBAL table_open_cache = 4000;"
echo "SET GLOBAL table_definition_cache = 2000;"
echo "SET GLOBAL tmp_table_size = 268435456;"
echo "SET GLOBAL max_heap_table_size = 268435456;"
echo "SET GLOBAL max_allowed_packet = 67108864;"
echo "SET GLOBAL interactive_timeout = 300;"
echo "SET GLOBAL wait_timeout = 300;"
echo ""
echo "3️⃣ Vérifier :"
echo "   SHOW VARIABLES LIKE 'max_connections';"
echo ""
echo "⚠️ IMPORTANT : Ces changements sont temporaires !"
echo "   Pour les rendre permanents, il faut modifier le fichier de configuration."
echo ""
echo "=================================================="
echo "Option 2 : Modifier le fichier de configuration (RECOMMANDÉ)"
echo "=================================================="
echo ""
echo "1️⃣ Trouver le fichier de config MySQL :"
echo "   ls /etc/mysql/mariadb.conf.d/"
echo "   ou"
echo "   ls /etc/mysql/my.cnf.d/"
echo ""
echo "2️⃣ Éditer le fichier :"
echo "   nano /etc/mysql/my.cnf"
echo "   ou"
echo "   nano /etc/mysql/mariadb.conf.d/50-server.cnf"
echo ""
echo "3️⃣ Ajouter ces lignes dans la section [mysqld] :"
echo ""
echo "[mysqld]"
echo "max_connections = 300"
echo "innodb_buffer_pool_size = 16G"
echo "innodb_buffer_pool_instances = 8"
echo "innodb_log_file_size = 512M"
echo "innodb_log_buffer_size = 64M"
echo "query_cache_type = 1"
echo "query_cache_size = 256M"
echo "query_cache_limit = 2M"
echo "max_allowed_packet = 64M"
echo "interactive_timeout = 300"
echo "wait_timeout = 300"
echo "thread_cache_size = 16"
echo "table_open_cache = 4000"
echo "table_definition_cache = 2000"
echo "tmp_table_size = 256M"
echo "max_heap_table_size = 256M"
echo ""
echo "4️⃣ Redémarrer MySQL :"
echo "   systemctl restart mysql"
echo "   ou"
echo "   systemctl restart mariadb"

